# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CICD

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:
    branches:
      - main
      - staging
      - dev


jobs:
  # The "build" job
  building-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: homervt/demo-github-actions
          # context: ./
          # file: ./Dockerfile
          # builder: ${{ steps.buildx.outputs.name }}
          # push: true
          tag_with_ref: true
          # cache-from: type=registry,ref=homervt/demo-github-actions
          # cache-to: type=inline
      
      - name: Deploy Image
        run: echo ${{ steps.docker_build.outputs.digest }}

      # - name: Build and Push Docker Image
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: homervt/demo-github-actions:latest
      #     cache-from: type=registry,ref=homervt/demo-github-actions:latest
      #     cache-to: type=inline

